# A string specifying the project ID, used for naming resources
project_id = "pitchlab-tempo"

[api]
# Port to use for the API URL
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage", "auth"]
# Extra schemas to add to the search_path of every request
extra_search_path = ["extensions"]
# Maximum rows to return from a view, table, or stored procedure
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322
# The database major version to use
major_version = 15
# Define multiple seed files
seed = [
  "migrations/house-seed/20240308_seed_agency_profiles.sql",
  "migrations/house-seed/20240308_seed_agency_branding.sql",
  "migrations/house-seed/20240308_seed_agency_credentials.sql",
  "migrations/house-seed/20240308_seed_team_members.sql",
  "migrations/house-seed/20240308_seed_team_members_2.sql",
  "migrations/house-seed/20240308_seed_services_1.sql",
  "migrations/house-seed/20240308_seed_services_2.sql",
  "migrations/house-seed/20240308_seed_services_3.sql",
  "migrations/house-seed/20240308_seed_services_4.sql",
  "migrations/house-seed/20240308_seed_case_studies_1.sql",
  "migrations/house-seed/20240308_seed_case_studies_2.sql",
  "migrations/house-seed/20240308_seed_case_studies_3.sql"
]

[studio]
# Port to use for Supabase Studio
port = 54323
# External URL of the API server that frontend connects to
api_url = "http://localhost"

[inbucket]
# Port to use for the email testing server's SMTP port
smtp_port = 54324
# Port to use for the email testing server's POP3 port
pop3_port = 54325

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB")
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used in emails
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week)
jwt_expiry = 3600
# Allow/disallow new user signups to your project
enable_signup = true

[analytics]
# Enable/disable analytics
enabled = false
# The port to use for the analytics server
port = 54327
# Vector port to use for the analytics server
vector_port = 54328 